mkdir part4 part5 part6
cd part4
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part4/Makefile
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part4/simd.c
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part4/simd.h
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part4/test_simd.c
cd ../part5
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/Makefile
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/omp_apps.c
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/omp_apps.h
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/server_utils.c
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/server_utils.h
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/timer.sh
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/dotp.c
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/hello.c
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/server.c
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/v_add.c
mkdir assets files libbmp libhttp
cd assets
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/assets/process.png
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/assets/sample_output.jpg
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/assets/threads.png
cd ../files
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/files/fruit.bmp
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/files/girl.bmp
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/files/lena.bmp
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/files/monarch.bmp 
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/files/template.html 
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/files/test.bmp
mkdir my_documents
cd my_documents
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/files/my_documents/click_here.txt
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/files/my_documents/credit.txt
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/files/my_documents/git-poem.jpg
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/files/my_documents/multi-processing.jpeg
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/files/my_documents/multithread-everything.jpeg 
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/files/my_documents/style.css
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/files/my_documents/theslowwinter.pdf
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/files/my_documents/wholesome_facts.txt
cd ../libbmp
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/libbmp/libbmp.c
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/libbmp/libbmp.h
cd ../libhttp
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/libhttp/libhttp.c
wget https://raw.githubusercontent.com/mmorri22/cse30321/main/homeworks/homework09/part5/libhttp/libhttp.h
cd ../../part6
cd ..
rm setup.sh